### 1. REGISTRAR O PRIMEIRO USUÁRIO (DONO)
POST http://localhost:3333/auth/register
Content-Type: application/json

{
  "email": "dono@meupdv.com",
  "name": "Dono do Restaurante",
  "password": "senhaforte123",
  "role": "DONO" 
}

### 2. FAZER LOGIN COM O USUÁRIO DONO
POST http://localhost:3333/auth/login
Content-Type: application/json

{
  "email": "dono@meupdv.com",
  "password": "senhaforte123"
}