### 3. TESTAR ROTA PROTEGIDA (DASHBOARD) COM TOKEN
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1NjlmOGE2Ny0yOTg5LTRkYWQtOWFkNS00M2ViMGQzMDg2ZTgiLCJyb2xlIjoiRE9OTyIsIm5hbWUiOiJEb25vIGRvIFJlc3RhdXJhbnRlIiwiaWF0IjoxNzYzMjQzMjMxLCJleHAiOjE3NjMzMjk2MzF9.ymIsZd3G3FGr3t6c34ycgHhm8hWLU8YhISysfCVSsCc

GET http://localhost:3333/dashboard/today
Authorization: Bearer {{token}}